name: Check semver
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semver:
    name: Check semver
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0 # We need the full history to compare against `main` for semver changes.

      - if: ${{ github.event_name != 'workflow_call' }}
        uses: ./.github/actions/rust
        with:
          tools: cargo-semver-checks
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.event_name == 'workflow_call' }}
        uses: mozilla/neqo/.github/actions/rust@main
        with:
          tools: cargo-semver-checks
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: nss-version
        run: echo "minimum=$(curl https://raw.githubusercontent.com/mozilla/nss-rs/refs/heads/main/min_version.txt)" >> "$GITHUB_OUTPUT"

      - if: ${{ github.event_name != 'workflow_call' }}
        uses: ./.github/actions/nss
        with:
          minimum-version: ${{ steps.nss-version.outputs.minimum }}

      - if: ${{ github.event_name == 'workflow_call' }}
        uses: mozilla/neqo/.github/actions/nss@main
        with:
          minimum-version: ${{ steps.nss-version.outputs.minimum }}

      - run: cargo semver-checks --default-features --baseline-rev origin/main -p mtu
